---
apiVersion: v1
kind: Secret
metadata:
  name: desubot-api-token
data:
  token: 123.... # Base64 encoded token.
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: desubot
spec:
  serviceName: "desubot"
  replicas: 1
  selector:
    matchLabels:
      app: desubot
  template:
    metadata:
      labels:
        app: desubot
    spec:
      containers:
      - name: desubot
        image: ultradesu/desubot:latest
        volumeMounts:
        - name: storage
          mountPath: /storage
        env:
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: desubot-api-token
              key: token
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi
